### PR TITLE
[cuda] merge latest ClaraGenomicsAnalsysis related improvements

### PR DESCRIPTION
**Pull request by tijyojwad**
1. Official support for cuda alignment. Using `--cudaaligner-batches` to run alignment on GPU. Tune batch number based on available memory on the GPU.
2. Improve CUDAPOA API for polishing, with better perf and reduced memory footprint.

### CODE REVIEW

**Comment by tijyojwad** [comment]
@rvaser did you get a chance to try this PR out?

**Comment by rvaser** [comment]
I have sent you a comparison between the old and new version via email. Will check the code out tomorrow. Sorry for waiting :/

**Comment by tijyojwad** [comment]
Hi @rvaser , any other changes needed for this?

**Comment by rvaser** [comment]
Not really. Should I merge this PR?

**Pull request merged**
