### PR TITLE
update to latest bioparser

### PR DESCRIPTION
**Pull request by mr-c**
to match spoa ~~4.0.5~~ 4.0.6

- [ ] https://github.com/rvaser/bioparser/pull/9

Would be nice if bioparser got a tagged release as well :-)

### CODE REVIEW

**Comment by mr-c** [comment]
Hmm.. the tests are stuck. Any hints? I'm not much a C++ programmer, to be clear.

**Comment by rvaser** [comment]
I'll investigate in a couple of days (and update everything up to date).

**Comment by mr-c** [comment]
@rvaser Thanks! This will help Debian keep spoa and racon up-to-date and in the archive.

**Comment by mr-c** [comment]
Closing in favor of @rvaser commits; thanks!

**Pull request closed without merging**
